<html>

<head>
    <meta name=Title content="">
    <meta name=Keywords content="">
    <meta http-equiv=Content-Type content="text/html; charset=macintosh">
    <style>
        <!--
        body {
            background-color: inherit;
            font-family: verdana, sans-serif;
            font-size: 10.0pt;
        }

        p {
            margin-bottom: 15px;
        }
        -->
    </style>
</head>

<body>

<div>

    <p>
		Dear ${title} ${surname},
	</p>

    <p>
		Your online account has been locked.
	</p>

    <p>
		For your security, your online account with Hodge Bank has been locked, because your password has been entered incorrectly multiple times.
    </p>

	<p>
		To unlock your account, please select the following link ${resetUrl}.
	</p>
	
    <p>
		If you haven't attempted to log in to your account, then please call our Customer Services Team on 0800 028 3746 (Monday-Friday 8am-8pm, Sunday 10am-4pm).
    </p>

    <p>
        Thank you.
    </p>

    <p>
        Hodge Bank Deposits Team
    </p>

    <p>
		This is an automated message, please do not respond to it. You can email our Customer Service Team via applications@hodgebank.co.uk
    </p>

</div>

</body>

</html>
