<html>
<head>
    <style>
        <!--
        body {
            background-color: inherit;
            font-family: verdana, sans-serif;
            font-size: 10.0pt;
        }

        p {
            margin-bottom: 15px;
        }

        p.double {
            margin-bottom: 30px;
        }
        -->
    </style>
</head>
<body>
<div>
    <p class="double">
        Dear ${title} ${surname},
    </p>

    <p class="double">
		This email confirms your recent account creation on the Hodge Bank Online Platform.
	</p>

	<p class="double">
		Kind regards,
	</p>

	<p>
		Hodge Bank
	</p>
</div>
</body>
</html>
