<html>

<head>
    <meta name=Title content="">
    <meta name=Keywords content="">
    <meta http-equiv=Content-Type content="text/html; charset=macintosh">
    <style>
        <!--
        body {
            background-color: inherit;
            font-family: verdana, sans-serif;
            font-size: 10.0pt;
        }

        p {
            margin-bottom: 15px;
        }
        -->
    </style>
</head>

<body>

<div>

    <p>
        Dear ${title} ${surname},
    </p>

    <p>
		${productName} - Important information about your application.
    </p>

    <p>
        Product Name: ${productName}<br/>
        Term: ${productTerm} year<br/>
        Interest Rate: ${interestRate}%
    </p>

    <p>
        As part of the application process, we must undertake a series of checks to confirm the identity of each applicant.
        Unfortunately this isn’t always possible, usually because the data sources we use don't hold sufficient information.
    </p>

    <p>
        In order to proceed, please provide a bank statement dated within the last 3 months.
        It needs to be for the bank account you'll use to fund your new savings account.
    </p>

    <p>
        Please send to the following free post address:
    </p>

    <p>
        Freepost<br/>
        HODGE BANK
    </p>

    <p>
        If you have any questions regarding your application please contact our Customer Service Team on 0800 028 3746
        (Monday-Friday 8am-8pm or 10am-4pm).
    </p>

    <p>
        Thank you for chosing Hodge Bank.
    </p>

    <p>
        Hodge Bank Deposits Team
    </p>

    <p>
        If you would like to view the Terms & Conditions and information about the Financial Services Compensation Scheme (FSCS) and your Personal Data, please visit Hodgebank.co.uk
    </p>

    <p>
        This is an automated message, please do not respond to it. You can email our Customer Service Team via deposits@hodgebank.co.uk
    </p>

</div>

</body>

</html>
