<html>
<head>
    <style>
        <!--
        body {
            background-color: inherit;
            font-family: verdana, sans-serif;
            font-size: 10.0pt;
        }

        p {
            margin-bottom: 15px;
        }

        p.double {
            margin-bottom: 30px;
        }
        -->
    </style>
</head>
<body>
<div>
    <p class="double">
        Dear ${title} ${surname},
    </p>

    <p>
		Please select the following link to continue the password reset process.
	</p>

    <p>
		<a href="${resetUrl}" rel="alternate">PASSWORD RESET LINK</a>
    </p>
		
    <p class="double">
		If you attempted to reset your password, or if you have any questions, then please contact our Customer Services Team anytime..
	</p>

	<p>
		Thank you,
	</p>

	<p class="double">
		Black Cell Limited.
	</p>
	
	<p>
		This is an automated message, please do not respond to it. You can email our Customer Service Team via noreply@blackcell.co.uk
	</p>
</div>
</body>
</html>
