<html>
<head>
    <style>
        <!--
        body {
            background-color: inherit;
            font-family: verdana, sans-serif;
            font-size: 10.0pt;
        }

        p {
            margin-bottom: 15px;
        }

        p.double {
            margin-bottom: 30px;
        }
        -->
    </style>
</head>
<body>
<div>
    <p class="double">
        Dear ${title} ${surname},
    </p>

    <p>
        Thank you for creating a security word. You now have access to your online account.
    </p>

    <p>
        For your account security, this word will be required each time that you login, so please ensure you remember it.
    </p>

    <p class="double">
        If you have any questions, please contact our Customer Services Team on 0800 028 3746 (Monday-Friday 8am-8pm, Sunday 10am-4pm).
    </p>

    <p>
        Thank you,
    </p>

    <p class="double">
        Hodge Bank Deposits Team
    </p>

    <p>
        This is an automated message, please do not respond to it. You can email our Customer Service Team via applications@hodgebank.co.uk.
    </p>
</div>
</body>
</html>