<html>
<head>
    <style>
        <!--
        body {
            background-color: inherit;
            font-family: verdana, sans-serif;
            font-size: 10.0pt;
        }

        p {
            margin-bottom: 15px;
        }

        p.double {
            margin-bottom: 30px;
        }
        -->
    </style>
</head>
<body>
<div>
    <p class="double">
        Dear ${title} ${surname},
    </p>

    <p>
		You have successfully requested a username reminder for your Hodge Bank online account.
	</p>

    <p>
		We can confirm it is ${userName}.
	</p>
		
    <p class="double">
		If this reminder was not requested by you, or you have any questions, please contact our Customer Service team on 0800 028 3746 (Monday-Friday 8am to 8pm and Sunday 10am to 4pm).
	</p>

	<p>
		Thank you,
	</p>

	<p class="double">
		Hodge Bank Deposits Team
	</p>
	
	<p>
		This is an automated message, please do not respond to it. You can email our Customer Service Team via applications@hodgebank.co.uk.
	</p>
</div>
</body>
</html>
